"""qURL Python SDK — secure, time-limited access links for AI agents."""

from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _pkg_version

from layerv_qurl.async_client import AsyncQURLClient
from layerv_qurl.client import QURLClient
from layerv_qurl.errors import (
    AuthenticationError,
    AuthorizationError,
    ConflictError,
    GoneError,
    NotFoundError,
    QURLError,
    QURLNetworkError,
    QURLTimeoutError,
    RateLimitError,
    ServerError,
    ValidationError,
)
from layerv_qurl.types import (
    QURL,
    AccessCode,
    AccessCodeListOutput,
    AccessGrant,
    AccessPolicy,
    AccessToken,
    AgentBootstrapOutput,
    AIAgentPolicy,
    APIKey,
    APIKeyListOutput,
    BatchCreateItem,
    BatchCreateOutput,
    BatchItemError,
    BatchItemResult,
    CheckDetail,
    CheckoutSession,
    ConnectorInstallation,
    ConnectorInstallationCapabilities,
    ConnectorInstallationListOutput,
    ConnectorInstallationStats,
    CreateOutput,
    CurrentPeriodUsage,
    Customer,
    DailyUsage,
    DNSRecord,
    Domain,
    DomainListOutput,
    DomainVerifyOutput,
    Invoice,
    InvoiceListOutput,
    ListOutput,
    MintOutput,
    NHPServerPeerInfo,
    PortalSession,
    Quota,
    QuotaPlan,
    QURLStatus,
    RateLimits,
    RedeemAccessCodeOutput,
    ResolveOutput,
    Resource,
    ResourceDetail,
    ResourceListOutput,
    ResourceType,
    Session,
    SessionListOutput,
    SessionTerminateOutput,
    TokenStatus,
    Usage,
    UsageCostEstimate,
    UsageDailyEntry,
    Webhook,
    WebhookDelivery,
    WebhookDeliveryListOutput,
    WebhookEventType,
    WebhookEventTypeInfo,
    WebhookEventTypesOutput,
    WebhookListOutput,
)

__all__ = [
    "AsyncQURLClient",
    "QURLClient",
    # Errors
    "AuthenticationError",
    "AuthorizationError",
    "ConflictError",
    "GoneError",
    "NotFoundError",
    "QURLError",
    "QURLNetworkError",
    "QURLTimeoutError",
    "RateLimitError",
    "ServerError",
    "ValidationError",
    # Types
    "AccessCode",
    "AccessCodeListOutput",
    "AIAgentPolicy",
    "AgentBootstrapOutput",
    "APIKey",
    "APIKeyListOutput",
    "BatchCreateItem",
    "BatchCreateOutput",
    "BatchItemError",
    "BatchItemResult",
    "CheckoutSession",
    "CheckDetail",
    "ConnectorInstallation",
    "ConnectorInstallationCapabilities",
    "ConnectorInstallationListOutput",
    "ConnectorInstallationStats",
    "CurrentPeriodUsage",
    "Customer",
    "DailyUsage",
    "DNSRecord",
    "Domain",
    "DomainListOutput",
    "DomainVerifyOutput",
    "Invoice",
    "InvoiceListOutput",
    "NHPServerPeerInfo",
    "PortalSession",
    "QuotaPlan",
    "QURLStatus",
    "RedeemAccessCodeOutput",
    "Resource",
    "ResourceDetail",
    "ResourceListOutput",
    "ResourceType",
    "Session",
    "SessionListOutput",
    "SessionTerminateOutput",
    "TokenStatus",
    "UsageCostEstimate",
    "UsageDailyEntry",
    "Webhook",
    "WebhookDelivery",
    "WebhookDeliveryListOutput",
    "WebhookEventType",
    "WebhookEventTypeInfo",
    "WebhookEventTypesOutput",
    "WebhookListOutput",
    "AccessGrant",
    "AccessPolicy",
    "AccessToken",
    "CreateOutput",
    "ListOutput",
    "MintOutput",
    "QURL",
    "Quota",
    "RateLimits",
    "ResolveOutput",
    "Usage",
]

try:
    __version__ = _pkg_version("layerv-qurl")
except PackageNotFoundError:
    __version__ = "dev"
