"""qURL Python SDK — protect a private URL once, then mint short-lived portal links for it.

A portal is cryptographic, just-in-time permission for one actor to reach
one private resource. Core flow: :meth:`QURLClient.protect_url` →
:meth:`ProtectedResource.create_portal`; programmatic openers use
:meth:`QURLClient.enter_portal`.
"""

from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _pkg_version

from layerv_qurl.async_client import AsyncProtectedResource, AsyncQURLClient
from layerv_qurl.client import ProtectedResource, QURLClient
from layerv_qurl.errors import (
    AuthenticationError,
    AuthorizationError,
    ConflictError,
    GoneError,
    NotFoundError,
    QURLError,
    QURLNetworkError,
    QURLTimeoutError,
    RateLimitError,
    ServerError,
    ValidationError,
)
from layerv_qurl.types import (
    QURL,
    AccessCode,
    AccessCodeListOutput,
    AccessGrant,
    AccessPolicy,
    AccessToken,
    AIAgentPolicy,
    APIKey,
    APIKeyListOutput,
    BatchCreateItem,
    BatchCreateOutput,
    BatchItemError,
    BatchItemResult,
    CheckDetail,
    CheckoutSession,
    ConnectorInstallation,
    ConnectorInstallationCapabilities,
    ConnectorInstallationListOutput,
    ConnectorInstallationStats,
    CreateOutput,
    CredentialClaim,
    CurrentPeriodUsage,
    Customer,
    DailyUsage,
    DNSRecord,
    Domain,
    DomainListOutput,
    DomainVerifyOutput,
    Invoice,
    InvoiceListOutput,
    ListOutput,
    MintOutput,
    Portal,
    PortalSession,
    Quota,
    QuotaPlan,
    QURLStatus,
    RateLimits,
    RedeemAccessCodeOutput,
    ResolveOutput,
    Resource,
    ResourceDetail,
    ResourceHandle,
    ResourceListOutput,
    ResourceType,
    Session,
    SessionListOutput,
    SessionTerminateOutput,
    TokenStatus,
    Usage,
    UsageCostEstimate,
    UsageDailyEntry,
    Webhook,
    WebhookDelivery,
    WebhookDeliveryListOutput,
    WebhookEventType,
    WebhookEventTypeInfo,
    WebhookEventTypesOutput,
    WebhookListOutput,
)

__all__ = [
    "AsyncProtectedResource",
    "AsyncQURLClient",
    "ProtectedResource",
    "QURLClient",
    # Errors
    "AuthenticationError",
    "AuthorizationError",
    "ConflictError",
    "GoneError",
    "NotFoundError",
    "QURLError",
    "QURLNetworkError",
    "QURLTimeoutError",
    "RateLimitError",
    "ServerError",
    "ValidationError",
    # Types
    "AccessCode",
    "AccessCodeListOutput",
    "AIAgentPolicy",
    "APIKey",
    "APIKeyListOutput",
    "BatchCreateItem",
    "BatchCreateOutput",
    "BatchItemError",
    "BatchItemResult",
    "CheckoutSession",
    "CheckDetail",
    "ConnectorInstallation",
    "ConnectorInstallationCapabilities",
    "ConnectorInstallationListOutput",
    "ConnectorInstallationStats",
    "CurrentPeriodUsage",
    "Customer",
    "DailyUsage",
    "DNSRecord",
    "Domain",
    "DomainListOutput",
    "DomainVerifyOutput",
    "Invoice",
    "InvoiceListOutput",
    "Portal",
    "PortalSession",
    "QuotaPlan",
    "QURLStatus",
    "RedeemAccessCodeOutput",
    "Resource",
    "ResourceDetail",
    "ResourceHandle",
    "ResourceListOutput",
    "ResourceType",
    "Session",
    "SessionListOutput",
    "SessionTerminateOutput",
    "TokenStatus",
    "UsageCostEstimate",
    "UsageDailyEntry",
    "Webhook",
    "WebhookDelivery",
    "WebhookDeliveryListOutput",
    "WebhookEventType",
    "WebhookEventTypeInfo",
    "WebhookEventTypesOutput",
    "WebhookListOutput",
    "AccessGrant",
    "AccessPolicy",
    "AccessToken",
    "CreateOutput",
    "CredentialClaim",
    "ListOutput",
    "MintOutput",
    "QURL",
    "Quota",
    "RateLimits",
    "ResolveOutput",
    "Usage",
]

try:
    __version__ = _pkg_version("qurl-python")
except PackageNotFoundError:
    __version__ = "dev"
